services:
  backend:
    build: ./backend
    command: # Number of gunicorn workers (w) should be (2 * CPU cores) + 1
      - bash
      - -c
      - |
        python manage.py migrate
        gunicorn wsgi -b :8000 -w 9 --max-requests 1000 --max-requests-jitter 100
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    environment:
      DJANGO_DEBUG: 'False'
      DB_HOST: ${DB_HOST}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - prod
      - dev
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/api/ping']
      interval: 10s
      retries: 5
      timeout: 10s

  frontend:
    build: ./frontend
    ports:
      - 5000:80 # For local testing
      - 80:80
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    restart: always
    profiles:
      - prod

  taskrunner:
    build: ./backend
    command:
      - bash
      - -c
      - |
        python manage.py run_background_tasks
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: ${CONTAINER_DB_HOST}
      DJANGO_DEBUG: 'False'
      LOG_FILE: 'debug-taskrunner.log'
      DB_CONN_MAX_AGE: 0
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    profiles:
      - prod
      - dev

volumes:
  postgres-data:
    driver: local
  matomo-db-data:
  matomo-data:
