// This file is auto-generated by @hey-api/openapi-ts

export type PatchedSchoolReadable = {
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    feideId?: string;
    displayName?: string;
    orgNumber?: string;
    owner?: string;
};

export type PatchedSchoolWritable = {
    feideId?: string;
    displayName?: string;
    orgNumber?: string;
    owner?: string;
};

export type SchoolReadable = {
    readonly id: string;
    readonly createdAt: string;
    readonly updatedAt: string;
    feideId: string;
    displayName: string;
    orgNumber: string;
    owner: string;
};

export type SchoolWritable = {
    feideId: string;
    displayName: string;
    orgNumber: string;
    owner: string;
};

export type SchoolsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schools/';
};

export type SchoolsListResponses = {
    200: Array<SchoolReadable>;
};

export type SchoolsListResponse = SchoolsListResponses[keyof SchoolsListResponses];

export type SchoolsCreateData = {
    body: SchoolWritable;
    path?: never;
    query?: never;
    url: '/schools/';
};

export type SchoolsCreateResponses = {
    201: SchoolReadable;
};

export type SchoolsCreateResponse = SchoolsCreateResponses[keyof SchoolsCreateResponses];

export type SchoolsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this school.
         */
        id: string;
    };
    query?: never;
    url: '/schools/{id}/';
};

export type SchoolsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SchoolsDestroyResponse = SchoolsDestroyResponses[keyof SchoolsDestroyResponses];

export type SchoolsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this school.
         */
        id: string;
    };
    query?: never;
    url: '/schools/{id}/';
};

export type SchoolsRetrieveResponses = {
    200: SchoolReadable;
};

export type SchoolsRetrieveResponse = SchoolsRetrieveResponses[keyof SchoolsRetrieveResponses];

export type SchoolsPartialUpdateData = {
    body?: PatchedSchoolWritable;
    path: {
        /**
         * A unique value identifying this school.
         */
        id: string;
    };
    query?: never;
    url: '/schools/{id}/';
};

export type SchoolsPartialUpdateResponses = {
    200: SchoolReadable;
};

export type SchoolsPartialUpdateResponse = SchoolsPartialUpdateResponses[keyof SchoolsPartialUpdateResponses];

export type SchoolsUpdateData = {
    body: SchoolWritable;
    path: {
        /**
         * A unique value identifying this school.
         */
        id: string;
    };
    query?: never;
    url: '/schools/{id}/';
};

export type SchoolsUpdateResponses = {
    200: SchoolReadable;
};

export type SchoolsUpdateResponse = SchoolsUpdateResponses[keyof SchoolsUpdateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};