# Generated by Django 4.2.20 on 2025-05-07 06:55

from django.db import migrations, models
import django.db.models.deletion
import mastery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('mastery_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feide_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feide_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=10)),
                ('org_number', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=200)),
                ('is_service_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('happens_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_value', models.IntegerField()),
                ('mastery_description', models.TextField(blank=True, null=True)),
                ('feedforward', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mastery.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feide_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=200)),
                ('group_subject_code', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('feide_id', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='mastery.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastery.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='mastery.user')),
            ],
            options={
                'unique_together': {('user', 'group', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='members', through='mastery.UserGroup', to='mastery.group'),
        ),
        migrations.CreateModel(
            name='StatusGoal',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastery.goal')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastery.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='status',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastery.user'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery_value', models.IntegerField()),
                ('mastery_description', models.TextField(blank=True, null=True)),
                ('feedforward', models.TextField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mastery.goal')),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_performed', to='mastery.user')),
                ('situation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mastery.situation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_received', to='mastery.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='mastery.school'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mastery.subject'),
        ),
        migrations.AddField(
            model_name='goal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mastery.group'),
        ),
        migrations.AddField(
            model_name='goal',
            name='previous_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mastery.goal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mastery.user'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(check=models.Q(('group__isnull', False), ('student__isnull', False), _connector='OR'), name='goal_group_or_student'),
        ),
    ]
