# Generated by Django 4.2.20 on 2025-05-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='feide_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='group_subject_code',
            new_name='group_code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_code',
            new_name='short_name',
        ),
    ]
