# Generated by Django 4.2.20 on 2025-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
