# Generated by Django 4.2.20 on 2025-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='feide_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='feide_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grep_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feide_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
