# Generated by Django 4.2.20 on 2025-10-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_goal_title_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
