# Generated by Django 4.2.20 on 2025-06-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
    ]
