# Generated by Django 4.2.20 on 2025-06-16 06:38

from django.db import migrations, models
import mastery.models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0002_alter_observation_options_alter_goal_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterySchema',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('schema', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='situation',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
