# Generated by Django 4.2.20 on 2025-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0002_school_is_goal_title_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteryschema',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
