# Generated by Django 4.2.20 on 2025-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0002_rename_feide_id_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
