# Generated by Django 4.2.20 on 2025-05-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0002_observation_observed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
