# Generated by Django 4.2.20 on 2025-08-06 12:56

from django.db import migrations, models
import django.db.models.deletion
import mastery.models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0002_goal_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='members', through='mastery.UserGroup', to='mastery.group'),
        ),
        migrations.CreateModel(
            name='DataMaintenanceTask',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintained_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('job_name', models.CharField(max_length=200)),
                ('target_id', models.CharField(max_length=200, null=True)),
                ('is_overwrite_enabled', models.BooleanField(default=False)),
                ('is_dryrun_enabled', models.BooleanField(default=False)),
                ('is_crash_on_error_enabled', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('result', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='mastery.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='mastery.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
