# Generated by Django 5.2.8 on 2025-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0003_masteryschema_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='members', through='mastery.UserGroup', through_fields=('user', 'group'), to='mastery.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(related_name='staff', through='mastery.UserSchool', through_fields=('user', 'school'), to='mastery.school'),
        ),
    ]
