# Generated by Django 4.2.20 on 2025-08-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0003_user_is_superadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='maintened_by_school',
            new_name='used_by_school',
        ),
    ]
