# Generated by Django 4.2.20 on 2025-05-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0003_observation_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='status',
            name='group',
        ),
        migrations.AddField(
            model_name='goal',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mastery.subject'),
        ),
        migrations.AddField(
            model_name='status',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mastery.subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StatusGoal',
        ),
    ]
