# Generated by Django 4.2.20 on 2025-06-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0003_masteryschema_alter_goal_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='mastery_schema',
        ),
        migrations.AddField(
            model_name='goal',
            name='mastery_schema_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mastery.masteryschema'),
        ),
    ]
