# Generated by Django 5.2.8 on 2025-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0004_alter_user_groups_alter_user_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(related_name='employees', through='mastery.UserSchool', through_fields=('user', 'school'), to='mastery.school'),
        ),
    ]
