# Generated by Django 4.2.20 on 2025-08-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0004_rename_maintened_by_school_subject_used_by_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='used_by_school',
            new_name='owned_by_school',
        ),
    ]
