# Generated by Django 4.2.20 on 2025-08-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0005_rename_used_by_school_subject_owned_by_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='owned_by_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owned_subjects', to='mastery.school'),
        ),
    ]
