# Generated by Django 5.2.8 on 2025-11-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0005_alter_user_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
