# Generated by Django 4.2.20 on 2025-06-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0005_goal_created_by_goal_maintained_at_goal_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='mastery_schema_id',
            new_name='mastery_schema',
        ),
    ]
