# Generated by Django 5.2.8 on 2025-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0006_goal_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamaintenancetask',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='masteryschema',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_service_enabled_for_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userschool',
            name='marked_for_deletion_at',
            field=models.DateTimeField(null=True),
        ),
    ]
