# Generated by Django 4.2.20 on 2025-06-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0006_rename_mastery_schema_id_goal_mastery_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masteryschema',
            old_name='schema',
            new_name='config',
        ),
    ]
