# Generated by Django 4.2.20 on 2025-08-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0006_alter_subject_owned_by_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='mastery.subject'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='mastery.subject'),
        ),
    ]
