# Generated by Django 5.2.8 on 2025-11-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0007_datamaintenancetask_marked_for_deletion_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamaintenancetask',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='masteryschema',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='situation',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='userschool',
            old_name='marked_for_deletion_at',
            new_name='deleted_at',
        ),
    ]
