# Generated by Django 4.2.20 on 2025-08-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0007_alter_goal_subject_alter_group_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='is_private',
            new_name='is_visible_to_student',
        ),
    ]
