# Generated by Django 5.2.8 on 2025-12-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0008_rename_marked_for_deletion_at_datamaintenancetask_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='mastery.group'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='mastery_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='mastery.masteryschema'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='previous_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mastery.goal'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='mastery.user'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='mastery.subject'),
        ),
    ]
