# Generated by Django 4.2.20 on 2025-08-28 12:22

from django.db import migrations, models
import django.db.models.deletion
import mastery.models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0008_rename_is_private_observation_is_visible_to_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='mastery.group'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='mastery_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='mastery.masteryschema'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='mastery.user'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='observations', to='mastery.goal'),
        ),
        migrations.AlterField(
            model_name='status',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='mastery.user'),
        ),
        migrations.AlterField(
            model_name='status',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='mastery.subject'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='mastery.role'),
        ),
        migrations.CreateModel(
            name='UserSchool',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintained_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='mastery.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schools', to='mastery.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schools', to='mastery.school')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='mastery.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schools', to='mastery.user')),
            ],
            options={
                'unique_together': {('user', 'school', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(null=True, related_name='staff', through='mastery.UserSchool', to='mastery.school'),
        ),
    ]
