# Generated by Django 5.2.8 on 2025-12-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0009_alter_goal_group_alter_goal_mastery_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='mastery.school'),
        ),
        migrations.AlterField(
            model_name='group',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mastery.school'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='mastery.subject'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='mastery.goal'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='owned_by_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_subjects', to='mastery.school'),
        ),
    ]
