# Generated by Django 4.2.20 on 2025-09-04 08:46

from django.db import migrations, models
import django.db.models.deletion
import mastery.models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0010_alter_user_schools_datamaintenancetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamaintenancetask',
            old_name='target_id',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='datamaintenancetask',
            name='is_dryrun_enabled',
        ),
        migrations.AddField(
            model_name='datamaintenancetask',
            name='job_params',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='datamaintenancetask',
            name='last_heartbeat_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datamaintenancetask',
            name='result',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='DataMaintenanceBot',
            fields=[
                ('id', models.CharField(default=mastery.models.generate_nanoid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintained_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='mastery.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='mastery.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datamaintenancetask',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_claimed', to='mastery.datamaintenancebot'),
        ),
    ]
