# Generated by Django 4.2.20 on 2025-09-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0011_rename_target_id_datamaintenancetask_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamaintenancetask',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
