# Generated by Django 4.2.20 on 2025-09-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0012_datamaintenancetask_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamaintenancetask',
            name='earliest_run_at',
            field=models.DateTimeField(null=True),
        ),
    ]
