# Generated by Django 5.2.8 on 2025-12-05 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0012_fix_mastery_schema_school_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='mastery.school'),
        ),
        migrations.AlterField(
            model_name='masteryschema',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_schemas', to='mastery.school'),
        ),
    ]
