# Generated by Django 5.2.8 on 2026-01-07 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0013_alter_goal_school_alter_masteryschema_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='estimated_at',
        ),
        migrations.AddField(
            model_name='status',
            name='begin_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='school',
            field=models.ForeignKey(default='asdf', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='mastery.school'),
            preserve_default=False,
        ),
    ]
