# Generated by Django 4.2.20 on 2025-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0013_datamaintenancetask_earliest_run_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamaintenancetask',
            name='claimed_by',
        ),
        migrations.AddField(
            model_name='datamaintenancetask',
            name='handler_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datamaintenancetask',
            name='earliest_run_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='DataMaintenanceBot',
        ),
    ]
