# Generated by Django 5.2.8 on 2026-01-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0014_remove_status_estimated_at_status_begin_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='mastery_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='mastery.masteryschema'),
        ),
    ]
