# Generated by Django 4.2.20 on 2025-09-08 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0014_remove_datamaintenancetask_claimed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamaintenancetask',
            name='earliest_run_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
