# Generated by Django 5.2.8 on 2026-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0015_status_mastery_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
