# Generated by Django 4.2.20 on 2025-09-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0015_alter_datamaintenancetask_earliest_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteryschema',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastery_schemas', to='mastery.school'),
        ),
        migrations.AlterField(
            model_name='masteryschema',
            name='title',
            field=models.CharField(default='Navnløst mestringsskjema', max_length=200),
        ),
    ]
