# Generated by Django 4.2.20 on 2025-09-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0016_masteryschema_school_alter_masteryschema_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
