# Generated by Django 5.2.8 on 2026-01-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0016_status_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_status_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
