# Generated by Django 5.2.8 on 2026-03-13 12:27

from django.db import migrations


def update_mastery_schema_config(apps, schema_editor):
    """
    Update all mastery_schema config fields:
    - Rename 'render_direction' key to 'value_input'
    - Change 'horizontal' value to 'sliderHorizontal'
    - Change 'vertical' value to 'sliderVertical'
    """
    MasterySchema = apps.get_model('mastery', 'MasterySchema')

    updated_count = 0
    for schema in MasterySchema.objects.all():
        if schema.config and 'render_direction' in schema.config:
            # Get the old value
            old_value = schema.config['render_direction']

            # Map old values to new values
            value_mapping = {
                'horizontal': 'sliderHorizontal',
                'vertical': 'sliderVertical',
            }

            # Update the value if it matches our mapping
            new_value = value_mapping.get(old_value, old_value)

            # Rename the key and update the value
            schema.config['value_input'] = new_value
            del schema.config['render_direction']

            schema.save()
            updated_count += 1

    print(f"Updated {updated_count} mastery schema config(s)")


def reverse_mastery_schema_config(apps, schema_editor):
    """
    Reverse the migration:
    - Rename 'value_input' key back to 'render_direction'
    - Change 'sliderHorizontal' back to 'horizontal'
    - Change 'sliderVertical' back to 'vertical'
    """
    MasterySchema = apps.get_model('mastery', 'MasterySchema')

    for schema in MasterySchema.objects.all():
        if schema.config and 'value_input' in schema.config:
            old_value = schema.config['value_input']

            # Reverse mapping
            value_mapping = {
                'sliderHorizontal': 'horizontal',
                'sliderVertical': 'vertical',
            }

            new_value = value_mapping.get(old_value, old_value)

            schema.config['render_direction'] = new_value
            del schema.config['value_input']

            schema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0017_school_is_status_enabled'),
    ]

    operations = [
        migrations.RunPython(update_mastery_schema_config, reverse_mastery_schema_config),
    ]
