# Generated by Django 4.2.20 on 2025-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0017_group_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subjects_allowed',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
