# Generated by Django 5.2.8 on 2026-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0018_update_mastery_schema_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteryschema',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
