# Generated by Django 4.2.20 on 2025-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0018_school_subjects_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_group_goal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_student_list_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
