# Generated by Django 5.2.13 on 2026-04-15 13:15

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def populate_observation_subject(apps, schema_editor):
    Observation = apps.get_model('mastery', 'Observation')
    Goal = apps.get_model('mastery', 'Goal')

    # Subquery: resolve subject directly from goal.subject
    goal_subject_sq = Subquery(
        Goal.objects.filter(id=OuterRef('goal_id')).values('subject_id')[:1]
    )

    # Subquery: resolve subject from goal.group.subject
    goal_group_subject_sq = Subquery(
        Goal.objects.filter(id=OuterRef('goal_id')).values('group__subject_id')[:1]
    )

    # First pass: goals with a direct subject
    Observation.objects.filter(
        subject__isnull=True,
        goal__subject__isnull=False,
    ).update(subject_id=goal_subject_sq)

    # Second pass: goals without a direct subject, but with a group subject
    Observation.objects.filter(
        subject__isnull=True,
        goal__group__isnull=False,
        goal__group__subject__isnull=False,
    ).update(subject_id=goal_group_subject_sq)


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0019_masteryschema_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(model_name='observation', name='situation',),
        migrations.AddField(
            model_name='observation', name='subject', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations',
                to='mastery.subject'),),
        migrations.RunPython(populate_observation_subject, migrations.RunPython.noop),
        migrations.DeleteModel(name='Situation',),]
