# Generated by Django 5.2.13 on 2026-04-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0021_alter_status_subject_statuscategory_status_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscategory',
            name='begin_at',
        ),
        migrations.RemoveField(
            model_name='statuscategory',
            name='end_at',
        ),
        migrations.AddField(
            model_name='statuscategory',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
