# Generated by Django 5.2.13 on 2026-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0022_remove_statuscategory_begin_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscategory',
            name='is_subject_specific',
            field=models.BooleanField(default=True),
        ),
    ]
