# Generated by Django 5.2.13 on 2026-05-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0023_statuscategory_is_subject_specific'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='observer',
        ),
    ]
