# Generated by Django 5.2.13 on 2026-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0025_rename_isvalueindicatorenabled_in_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_create_enabled_for_students',
            field=models.BooleanField(default=False),
        ),
    ]
