# Generated by Django 5.2.13 on 2026-08-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0026_school_is_create_enabled_for_students'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datamaintenancetask',
            index=models.Index(fields=['created_at'], name='datamaintenancetask_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='datamaintenancetask',
            index=models.Index(fields=['updated_at'], name='datamaintenancetask_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='datamaintenancetask',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='datamaintenancetask_deleted_at_null_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='group_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['updated_at'], name='group_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='group_deleted_at_null_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryschema',
            index=models.Index(fields=['created_at'], name='masteryschema_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryschema',
            index=models.Index(fields=['updated_at'], name='masteryschema_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryschema',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='masteryschema_deleted_at_null_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['created_at'], name='role_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['updated_at'], name='role_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='role_deleted_at_null_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['created_at'], name='school_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['updated_at'], name='school_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='school_deleted_at_null_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['created_at'], name='subject_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['updated_at'], name='subject_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='subject_deleted_at_null_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['updated_at'], name='user_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='user_deleted_at_null_idx'),
        ),
    ]
