# Generated by Django 5.2.13 on 2026-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0027_datamaintenancetask_datamaintenancetask_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='product_url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
