# Generated by Django 5.2.13 on 2026-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0028_observation_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ui_translations',
            field=models.JSONField(null=True),
        ),
    ]
