# Generated by Django 5.2.13 on 2026-09-23 06:25

import mastery.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0029_school_ui_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteryschema',
            name='config',
            field=mastery.fields.PlainJSONField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ui_translations',
            field=mastery.fields.PlainJSONField(null=True),
        ),
    ]
