export const TEACHER_ROLE = 'teacher'
export const STUDENT_ROLE = 'student'
export const SCHOOL_ADMIN_ROLE = 'admin'
export const SUBJECTS_ALLOWED_ALL = 'all'
export const SUBJECTS_ALLOWED_CUSTOM = 'only-custom'
export const SUBJECTS_ALLOWED_GROUP = 'only-group'
